version: "3.8"

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontendTesting
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:3001
    command: sh -c "npm run dev"
  mock-api:
    build:
      context: ./frontend
      dockerfile: Dockerfile.mock-api
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run start:mock-api
    ports:
      - "3001:3001"
