services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: password

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontendTesting
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm run dev"
