services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: password

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - spring-boot-app
    ports:
      - "80:80"
