version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: eM^j@$KVn)!5ZC!N
      POSTGRES_USER: myuser
    ports:
      - "5432"

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: eM^j@$KVn)!5ZC!N

  # react-app:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   environment:
  #     NODE_ENV: production
