services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"

  backend:
    image: "maxjasz/fit3162-19-backend:latest"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: password
      LOGGING_LEVEL_ROOT: "info"

  frontend:
    image: "maxjasz/fit3162-19-frontend:latest"
    depends_on:
      - backend
    ports:
      - "80:80"
